#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define IDD_ABOUTDIALOG                         101
#define IDR_ACCELERATOR1                        102
#define IDS_TIPS_NEW                            200
#define IDM_NEW                                 300
#define ID_ABOUTDIALOG_OK                       10000
#define ID_ABOUTDIALOG_VIEWONGITHUB             10002
#define ID_ABOUTDIALOG_CHECKFORUPDATES          10003
#define ID_FILE_NEW                             40000
#define ID_FILE_OPEN                            40001
#define ID_FILE_SAVE                            40002
#define ID_FILE_SAVEAS                          40003
#define ID_FILE_EXIT                            40004
#define ID_EDIT_CUT                             40005
#define ID_EDIT_COPY                            40006
#define ID_EDIT_PASTE                           40007
#define ID_EDIT_SELECTALL                       40008
#define ID_EDIT_DESELECTALL                     40009
#define ID_VIEW_STATUSBAR                       40010
#define ID_VIEW_WORDWRAP                        40011
#define ID_VIEW_TOOLBAR                         40012
#define ID_FORMAT_FONT                          40013
#define ID_FORMAT_DEFAULTFONT                   40014
#define ID_FONT_BOLD                            40015
#define ID_FONT_ITALICS                         40016
#define ID_FONT_UNDERLINE                       40017
#define ID_FONT_STRIKETHROUGH                   40018
#define ID_HELP_GETHELP                         40019
#define ID_HELP_ABOUT                           40020
#define ID_HELP_CHECKFORUPDATES                 40021
#define ID_HELP_VIEWONGITHUB                    40022
#define ID_VIEW_DEBUGWINDOW                     40023
#define ID_EDIT_UNDO                            40024
#define ID_EDIT_REDO                            40025
#define ID_EDIT_CLEAR                           40026
#define ID_VIEW_REFRESHWINDOW                   40027
